entrance:
  - pressure: bmp180
  - humidity: dht22
  - altitude: bmp180
  - temperature:
    - bmp180
    - dht22 
living_room:
  - humidity: dht22
  - altitude: bmp180
  - light: grove_TMG39931
  - pressure:
    - bmp180
    - sense_hat
  - temperature:
    - bmp180
    - dht22